# Generated by Django 5.2.7 on 2025-12-08 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_remove_event_date_remove_event_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('planned', 'Запланировано'), ('in_progress', 'В работе'), ('done', 'Завершено'), ('cancelled', 'Отменено')], default='planned', max_length=20),
        ),
    ]
