# Generated by Django 5.2.7 on 2025-12-17 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_notificationsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='telegram_message_1day_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID сообщения за 1 день'),
        ),
        migrations.AddField(
            model_name='event',
            name='telegram_message_3days_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID сообщения за 3 дня'),
        ),
    ]
